name: Test workflow
on:
  pull_request:
    types:
      - opened
      - closed
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get closed
        uses: actions/checkout@v5
      - name: Output data
        run: echo "${{ toJSON(github.event) }}"
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Deploying
        run: echo "Deploying ......."
