name: My Normal Workflow
on: [ push, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "First step"
      - name: Second step
        run: echo "Second step"
  build:
    needs: test
    uses: ./.github/workflows/reusable.yml
    with:
      artifact_name: dist-FILE
  show:
    needs: build
    steps:
      - name: show me output variable
        run: echo "${{ jobs.build.outputs.my_var }}"